### PR TITLE
`mount.s3ql` now exits gracefully on CTRL-C (INT signal)

### PR DESCRIPTION
**Pull request by d--j**

### CODE REVIEW

**Comment by d--j** [comment]
There is a race condition – with this code S3QL only exits gracefully it's inside the main loop of pyfuse3. Do we live with this timing problem?

**Comment by Nikratio** [comment]
Do I understand correctly that Ctrl+C prior to pyfuse3 main gives a "non-graceful" exit with a KeyboardInterrupt stacktrace?

My suggestion would be to instead use `https://docs.python.org/3.8/library/signal.html#signal.pthread_sigmask` to block SIGINT as one of the very first things on startup, and then unblock it in the try block just before calling pyfuse3.main.

**Comment by Nikratio** [comment]
You probably also want to re-block it after exiting pyfuse3, because otherwise there is a second race where Ctrl+C after pyfuse3.main() can interrupt the metadata upload.

**Comment by d--j** [comment]
> Do I understand correctly that Ctrl+C prior to pyfuse3 main gives a "non-graceful" exit with a KeyboardInterrupt stacktrace?

yes

> My suggestion would be to instead use `https://docs.python.org/3.8/library/signal.html#signal.pthread_sigmask` to block SIGINT as one of the very first things on startup, and then unblock it in the try block just before calling pyfuse3.main.
>
> You probably also want to re-block it after exiting pyfuse3, because otherwise there is a second race where Ctrl+C after pyfuse3.main() can interrupt the metadata upload.


This should be implemented now – very exotic timings might get `mount.s3ql` to exit non-gracefully but other than that it should be fairly safe to exit S3QL via CTRL-C now.

**Pull request merged**
