### PR TITLE
remove empty s3ql data directories

### PR DESCRIPTION
**Pull request by hwertz**
I found over time my s3ql_data_ directory had many man empty directories -- 100,000s of them.  This patch will attempt to remove the storage directory when a block is deleted; if the directory is empty, it removes the directory successfully; if it's not empty, the os.rmdir returns an error which is harmlessly trapped; if it's empty but a race condition means something was going to put a file in there (.. if that's possible) it throws a "FileNotFoundError", I set this to be treated as a temporary error, so it'll treat it just like S3 etc. not taking a block and retry it. 

I had a huge reduction in fsck.s3ql run time, on one (spinning rust) drive it cut my time from 3 or 4 hours to about 10 minutes.  Besides the obvious speedup of not having to walk through in my case about 800,000 empty directories (about 90% of the total), I also had additional speedup because the directory tree metadata now fits in Linux VFS cache whereas before it wasn't even close.

To clean my s3ql-data I just changed into the s3ql-data/ directory and ran "find -type d -exec rmdir -p {} \+", which took rather a long time (I ran it overnight..) but cleaned it out nicely.  That is probably not safe to run on a live filesystem with existing s3ql but would be with this one since any "rmdir race" will be treated as a retryable temporary error.
Thanks
--Henry

### CODE REVIEW

**Review by hwertz — COMMENTED** [review]
Fixed typo.

**Comment by hwertz** [comment]
I used a line of shell script to remove my excess directoriesI could see doing a "maintenance run" of removing empty directories inside fsck.s3ql, where it already walks through the whole directory tree anyway.  Or a small contrib script to do it.

**Comment by hwertz** [comment]
tests/t1_backends.py does post-test cleanup that tries to remove a directory that this s3ql patch already removes, so I wrapped the directory removal in a try/except block; t3_verify.py has similar cleanup code that I also wrapped.

Moved down the object deleteon in  t3_fsck's test_tmpfile, it creates an object, deletes that object (at which point s3ql now removes the object's storage directory), then attempts to put a .tmp file into the just-removed directory.  It now removes the object after the .tmp file is created so the directory is not prematurely removed.

**Comment by hwertz** [comment]
Took a few tries to successfully catch the DanglingStorageURLException in the t4_adm.py test_clear test but got it (it creates a filesystem, uses s3qladm to clear it, and then attempts to attach a new backend to it and verify the block list is empty; but s3ql now removes the directory when the last file is removed.   The failure to create a backend with DanglingStorageURLException still indicates the s3qladm clear worked so the test is still performed.

**Comment by Nikratio** [comment]
Thanks for working on this!

I don't much like the way we have to consider ENOENT a "temporary error " and re-try.

What would be the disadvantages of keeping everything as-is during normal operation, and doing the cleanup as part of the fsck.s3ql (or, if necessary, as a one-off operation on filesystem mount)? If I understand correctly, the empty directories do not matter for mount.s3ql. Or do they?

If this doesn't work, then I think we should be able to take advantage of the fact that object numbers are monotonically increasing. In other words, if the current object number is incompatible with the prefix directory that we are about to delete, then we can remove it safely. If it's not, then we can just defer leave the directory as-is.

What do you think?

**Comment by hwertz** [comment]
Disadvantages?  None whatsoever.   I think it'd be totally sensible to have fsck.s3ql remove the empty directories,  it's walking through the directory tree (with os.walk) already to remove backend .tmp files, that'd be the perfect spot to put an os.rmdir.  Nice and clean.  I see a close analogy for this, fsck.ext4 does some directory optimizations, it'd probably be possible but quite complicated to have ext4 try to do these optimizations "on the fly.".

mount.s3ql doesn't care if the directories are there or not -- the local backend runs os.makedirs when it's writing anything in.   For read, delete, etc., it directly calculates the path it expects to find the file in.  I got a minor speedup from ext4 being able to look up each file a hair faster (quite a few of the directories that had 900 subdirectories in them, a few still have 100s but many have 0 to a few dozen subdirectoires.  I must have ended up with a lot of removed blocks over time.)
Thanks!
--Henry

**Comment by Nikratio** [comment]
Well, then let's just do it during fsck.s3ql. That should avoid the problem with the race condition.

**Comment by hwertz** [comment]
Sounds good!  I'll revert these patches and patch up fsck.  I don't think it should log one line per removed directory (I had 100,000s of directories  in mine, it'd get a bit excessive) or log nothing at all.   I figured I'd change the fsck text to 'Checking for temporary objects and empty directories (backend)...', and when it's done write out self.log_error('Removed %d empty directories')  I won't set self.found_errors (empty directories are a normal consequence of mount.s3ql operation and having the directories there or not does not affect data integrity,)
 
I have a test filesystem on here with like 5MB or so files in it, so I can stick some empty directories and .tmp files into _s3ql_data_ and make sure patched fsck does it's thing and the output looks nice.
Thanks!
--Henry

**Comment by hwertz** [comment]
Oops.  Well, I removed the branch and recreated it, this closed the pull request.  I've got the new patch ready, I'll put in a new pull request with it.

**Pull request closed without merging**
