### PR TITLE
Add Onezone IA storage class for AWS backend

### PR DESCRIPTION
**Pull request by pheanex**
As mentioned in #77 
How is this for a first try?
Would like to add some tests for this, but not sure how => any suggestions?

### CODE REVIEW

**Comment by Nikratio** [comment]
Looks good, thanks! I don't think you can add a good unit test for this. Have you tested it locally and confirmed (eg with the AWS Console) that the objects are stored with the right class?

**Comment by pheanex** [comment]
Yes, i just tested it with a new aws s3 bucket (See screenshot)
` mkfs.s3ql s3://eu-central-1/<bucketname> --backend-options oia`
one_zone_oia

**Comment by Nikratio** [comment]
Great! Just one more thing: please also update the `Changes.txt` file to mention this new feature.

**Comment by pheanex** [comment]
Sure. Do I still add this to 3.0 and update the date, or do I start a new version?

**Comment by Nikratio** [comment]
Please add a new entry with version "UNRELEASED"

**Pull request merged**
