### PR TITLE
add mount option to specify a custom file system name

### PR DESCRIPTION
**Pull request by jlippuner**

### CODE REVIEW

**Comment by Nikratio** [comment]
Thanks for the patch! But could you elaborate on the use case? The file system type is S3QL, why would you want to change it?

**Comment by jlippuner** [comment]
When I run `df`, the original S3QL file system name was much longer than all the other names and it just made the output of `df` a bit harder to read (my storage url was something like `local:///some/very/long/absolute/path` which got put into the file system name). So I wanted to be able to change the name to something shorter :)

**Comment by Nikratio** [comment]
Sorry for the delay... I just can't make up my mind if this is worth adding for other people, or if it's gonna end up being used by just you.

**Comment by Nikratio** [comment]
Given the lack of interest from anyone else, I am not going to merge this. Please do not take it personally! There's an actual cognitive cost for each extra option, and this just does not seem worth it.

**Pull request closed without merging**
