### PR TITLE
check available disk space before writing cache entry

### PR DESCRIPTION
**Pull request by powerpaul17**
Also consider the cache full if there is not enough disk space left.

### CODE REVIEW

**Comment by Nikratio** [comment]
I'm not sure if this is worth it, this means at least one extra statf() syscall for every write.

**Comment by powerpaul17** [comment]
Yes, it was just a quick solution because I supposed that there is a check anyway and then realized that things break when I set the cache size greater than the available disk space.
Maybe there is another possibility to deal with it?

**Comment by Nikratio** [comment]
I think the "better" solution is to rely on the user to make sure that there remains as much free disk space as they specify that S3QL should use.

**Comment by powerpaul17** [comment]
While I respect your point of view, I disagree. As a user, I expect S3QL to work even if for some reason the disk holding the cache becomes full. That's what I was expecting until I found out that it simply crashes.

But I can of course always keep my patch on top of the source, so no problem for me, just thought it might be useful for others as well..

**Comment by Nikratio** [comment]
I agree with the philosophy, S3QL should work if the cache becomes full. I just think this particular solution is not the right one.

If someone creates a pull request that e.g. catches ENOSPACE errors *if they happen* (instead of checking for available space before *every* write) and then takes appropriate action (eg forward the error to user space, or block until the cache has been trimmed), I'd probably apply them.

**Comment by powerpaul17** [comment]
Thanks for this useful hint, I might have a look into that. :slightly_smiling_face: Also seems like a more elegant solution.

**Pull request closed without merging**
