### PR TITLE
Add test for issue fixed by #234

### PR DESCRIPTION
**Pull request by r0ps3c**

### CODE REVIEW

**Comment by Nikratio** [comment]
Thanks! Could you please remove the unrelated changes (changed quoting characters etc)?

**Comment by r0ps3c** [comment]
> Thanks! Could you please remove the unrelated changes (changed quoting characters etc)?

Committed an update to address this so should be ready to go.

**Comment by Nikratio** [comment]
Have you checked if the test is actually run? Looking at the CI output, I don't see it. I think within a test class, test_* methods may not be executed automatically.

**Comment by r0ps3c** [comment]
> Have you checked if the test is actually run? Looking at the CI output, I don't see it. I think within a test class, test_* methods may not be executed automatically.

I checked by running `python3 -m pytest tests` during local development, and see the test executed by travis at, for example,  https://travis-ci.com/github/s3ql/s3ql/jobs/486718964#L1168. The documentation for pytest (e.g. https://docs.pytest.org/en/stable/reference.html#confval-python_functions) also suggests test_ methods will be run.

**Comment by Nikratio** [comment]
Sorry, I missed the fact that you modified t5_cp.py rather than just t4_fuse.py!

**Pull request merged**
