### PR TITLE
Travis integration

### PR DESCRIPTION
**Pull request by szepeviktor**
@nikratio Travis uses virtualenvs.

Please see some C errors: https://travis-ci.org/szepeviktor/s3ql/jobs/266302599#L906-L921

Code: https://github.com/s3ql/s3ql/blob/master/src/s3ql/deltadump.pyx#L512-L513

### CODE REVIEW

**Comment by szepeviktor** [comment]
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

**Comment by szepeviktor** [comment]
Inserting `#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"` at deltadump.c:6677 is a work-around.

**Comment by szepeviktor** [comment]
C error solved.

The last test fails now: https://travis-ci.org/s3ql/s3ql/jobs/266321018#L1150

**Comment by Nikratio** [comment]
Thanks! Looks like Python 3.3 is broken on Travis, I just disabled building for that.

The other issue is a known problem. Unfortunately it only happens sporadically, and I haven't been able to reproduce it locally yet.

**Comment by Nikratio** [comment]
I've created https://bitbucket.org/nikratio/s3ql/issues/272/t3_verifypy-test_retrieve-sometimes-fails for this.

**Comment by szepeviktor** [comment]
Thank you.

**Pull request merged**
