### PR TITLE
Require modern attrs

### LINKED ISSUE #136: CI fails: outcome vs. attrs
> outcome 1.0.1 has requirement attrs>=19.2.0, but you'll have attrs 18.2.0 which is incompatible.

https://travis-ci.org/s3ql/s3ql/jobs/616359971

### PR DESCRIPTION
**Pull request by szepeviktor**
https://github.com/python-attrs/attrs/releases

Fixes #136

### CODE REVIEW

**Comment by szepeviktor** [comment]
@Nikratio Success.

Remaining issue: #134

**Comment by szepeviktor** [comment]
Somehow attrs stays at an older version.

**Comment by Nikratio** [comment]
I think this is superseded by #151

**Comment by szepeviktor** [comment]
Yes.

**Pull request closed without merging**
