### PR TITLE
Use coveralls for test/code coverage details

### PR DESCRIPTION
**Pull request by r0ps3c**
I've found, and seen in other projects, that a simple measure of code/test coverage helps to ensure adequate test cases, both for existing as well as new code.

### CODE REVIEW

**Comment by r0ps3c** [comment]
The failure is due to missing authentication token/authorization for coveralls.io. As this will continue to fail until a committer sets this, what's the preferred approach? Should I alter the code/PR to skip submission for now?

**Comment by Nikratio** [comment]
I think I've given coveralls.io access now. Could you try again? If it doesn't work, could you give me exact instructions on what I need to do?

**Comment by Nikratio** [comment]
...and thanks for working on this!

**Comment by r0ps3c** [comment]
Thanks @Nikratio - closing and reopening to get travis to rerun tests and check it all works properly.

**Comment by r0ps3c** [comment]
Looks like travis is making some changes/performing maintenance that could be causing issues. I'm going to close this for now until I can confirm everything is working again.

**Comment by r0ps3c** [comment]
Re-opening, now that I've had a chance to look at and confirm all should be working.

**Pull request closed without merging**
