### PR TITLE
Test on all supported Python versions

### PR DESCRIPTION
**Pull request by szepeviktor**
> Python 3.3.0 or newer. Make sure to also install the development headers.

### CODE REVIEW

**Comment by szepeviktor** [comment]
@Nikratio 3.7-dev could be "allow-fail" but 3.3 fails like this:
https://travis-ci.org/s3ql/s3ql/jobs/399265680#L1017

Could you suggest a solution?

**Comment by Nikratio** [comment]
Looks like the most recent defusedxml version doesn't support Python 3.3 any longer...

**Comment by szepeviktor** [comment]
Thank.

Strange that `pip install defusedxml` installs a python package on a Python version that it is not compatible with.

> Drop support for Python 2.6, 3.1, 3.2, 3.3

https://pypi.org/project/defusedxml/

**Comment by szepeviktor** [comment]
@Nikratio Please merge.

**Pull request merged**
